//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Book
    {
        public int Bid { get; set; }
        public string BPic { get; set; }
        public string Bname { get; set; }
        public string ISBN { get; set; }
        public Nullable<int> KC { get; set; }
        public Nullable<decimal> Pirce { get; set; }
    }
}
