//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class A3189Entities : DbContext
    {
        public A3189Entities()
            : base("name=A3189Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Book> Book { get; set; }
        public virtual DbSet<Classss> Classss { get; set; }
        public virtual DbSet<Student> Student { get; set; }
        public virtual DbSet<Trees> Trees { get; set; }
        public virtual DbSet<Types> Types { get; set; }
    }
}
